name: TerraXplora
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ["7.0", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Use MongoDB from Github actions
        uses: SusanDoggie/mongodb-action@0.0.1
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
